name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
  
    - name: Install Terraform
      run: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
    
    - name: Create SSH key
      run: |
        mkdir -p /home/ec2-user/.ssh
        chmod 600 /home/ec2-user/.ssh
        echo "$TF_VAR_deploy_key" > /home/ec2-user/.ssh/id_rsa
        chmod 600 /home/ec2-user/.ssh/id_rsa
        ssh-keyscan github.com >> /home/ec2-user/.ssh/known_hosts
      shell: bash 
      env:
        TF_VAR_deploy_key: ${{ secrets.DEPLOY_KEY }}